build:
  version: "1.0"

accounts:
  message: "Welcome to config client related prod APIs "
  contactDetails:
    name: "MT - Product Owner"
    email: "mt@eazybank.com"
  onCallSupport:
    - (555) 123-1234
    - (555) 123-1345
