build:
  version: "1.0"

accounts:
  message: "Welcome to config client related monitor APIs "
  contactDetails:
    name: "MT - Product Owner"
    email: "{cipher}7d1b443eb715c690f1505f6d291856baba400da4692985792d98050f5f25f7c9"
  onCallSupport:
    - (555) 123-1234
    - (555) 123-1345
